version: '2'
services:
  source_data:
    image: busybox
    volumes:
      - ./:/var/www/html
  webserver:
    build: .docker/webserver
    ports:
      - "8080:80"
    volumes_from:
      - source_data
  php-fpm:
    build: .docker/php-fpm
    depends_on:
      - db
    expose:
      - 9000
    links:
      - db
    volumes_from:
      - source_data
  db:
    build: .docker/db
    environment:
      MYSQL_ROOT_PASSWORD: dcpp
      MYSQL_DATABASE: docker_compose_pet_project
      MYSQL_USER: dcpp
      MYSQL_PASSWORD: dcpp
    ports:
      - "3366:3306"
    restart: always
  cli:
    build: .docker/cli
    links:
      - db
      - webserver
      - php-fpm
      - source_data
    volumes_from:
      - source_data